/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (4.0.2).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package it.intesys.jhipsterconf.client.petstore.api;

import it.intesys.jhipsterconf.client.petstore.model.Pet;
import it.intesys.jhipsterconf.client.petstore.model.Problem;
import io.swagger.annotations.*;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2019-06-27T15:02:47.730+02:00[Europe/Berlin]")

@Validated
@Api(value = "WritePets", description = "the WritePets API")
public interface WritePetsApi {

    @ApiOperation(value = "Create a pet", nickname = "createPets", notes = "", authorizations = {
        @Authorization(value = "jwt")
    }, tags={ "Write Pets", })
    @ApiResponses(value = { 
        @ApiResponse(code = 201, message = "Null response"),
        @ApiResponse(code = 200, message = "unexpected error", response = Problem.class) })
    @RequestMapping(value = "/pets",
        produces = "application/json", 
        consumes = "application/json",
        method = RequestMethod.POST)
    ResponseEntity<Void> createPets(@ApiParam(value = "The pet to create" ,required=true )  @Valid @RequestBody Pet pet);

}
